#!/bin/bash

if [ $# -eq 0 ]
    then
        echo "please pass the url to which the players should connect as argument";
        exit 1;
fi

DANGEROUSLY_DISABLE_HOST_CHECK=true node server/index.js $@ &
DANGEROUSLY_DISABLE_HOST_CHECK=true npm start
